### ISSUE TITLE
Criar ROTAS de Presença (olhar comentários dentro desse card)

### ISSUE THREAD

**Issue by Taisbruno** [Taisbruno/chamada-inteligente-uff#49]

**Comment by Taisbruno** [comment]
Rota (POST): inserir presença manual
Rota (PUT): alterar presença manual (invalidar, validar)
ROTA (PUT): recebe atestado e mensagem e envia o atestado para o S3 e salvar link do atestado no s3 e mensagem no banco

OBS1: LER OS REQUISITOS DO PROJETO PORQUE NEM TODAS AS ROTAS FORAM MAPEADAS!! LEIA OS REQUISITOS E IMPLEMENTE O QUE FOR NECESSÁRIO PARA QUE ESSA API ATENDA AO QUE O PROJETO PRECISA!

OBS2: ESSA ANÁLISE FOI FEITA POR ALTO, LOGO, NÃO NECESSARIAMENTE AS ROTAS QUE PENSEI ESTÃO CORRETAS OU POSSUEM TUDO QUE PRECISAREMOS, TUDO ESTÁ SUJEITO A POSSÍVEIS ALTERAÇÕES CASO QUEM ESTÁ IMPLEMENTANDO OPTE POR SEGUIR UM CAMINHO DIFERENTE.

**Comment by andre-baIbi** [comment]
Rota (POST): inserir presença manual (**FEITA**)
Rota (PUT): alterar presença manual (invalidar, validar) (**FEITA**)
ROTA (PUT): recebe atestado e mensagem e envia o atestado para o S3 e salvar link do atestado no s3 e mensagem no banco

**Comment by andre-baIbi** [comment]
Rota (POST): inserir presença manual (FEITA)
Rota (PUT): alterar presença manual (invalidar, validar) (FEITA)
~~ROTA (PUT): recebe atestado e mensagem e envia o atestado para o S3 e salvar link do atestado no s3 e mensagem no banco~~
**ROTA (PUT): recebe atestado e mensagem e envia o atestado para o banco em base64 e salvar mensagem no banco**
